### ISSUE TITLE
Livesplit is slow with latest version

### ISSUE THREAD

**Issue by sillypears** [BR-/LiveSplit.Bleed2#1]
Hey, so I have tried using the autosplitter for some of my runs but as soon as I click activate, it takes 4-5 seconds for anything to register in Livesplit. Not sure if anyone else has this issue. Not only is it an issue with navigating the UI of livesplit but splits are also slow. 

I've never seen this issue with other ASL files, and the last version I tried (where it would complete the run after warship) didn't have this problem. 

Not sure if anyone else has the issue also, or if there is a way to fix it. 

Thanks!

**Comment by BR-** [comment]
I think I fixed it, can you try now?

**Comment by sillypears** [comment]
It's working much better for me! Thank you!!
